words = [
    "brianshumate",
    "CODESIGN",
    "CREAT",
    "Hashi",
    "Homebrew",
    "launchctl",
    "LSUI",
    "nspasteboard",
    "qmd",
    "Sonoma",
    "TEAMID",
    "vmenuhelper",
    "XPC"
]
